name: Pull request validation
on:
  pull_request:

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run linters & tests
        run: npm test --if-present
      - name: Build projects
        run: npm run build
      - name: Build website
        run: npm run build:website
